### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [algebra2boy/Swift#1]
Thanks for submitting your prework assignment. Upon our review of your work, we noticed that the GIF or recording included in your submission did not show the following features:

 - The segmented control matches the text in the alert box.
 - An alert box shows all of the information the students have inputted.

This made your assignment incomplete. Kindly record another demo **showing all required features.** Once done, resubmit your assignment in the application dashboard.

**Comment by algebra2boy** [comment]
Hi, thanks for the constructive feedback. I have fixed all the features.
